version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  eb-build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Assemble JAR
          command: |
            # Skip this for other nodes
                  if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                    ./gradlew assemble
                  fi
            # As the JAR was only assembled in the first build container, build/libs will be empty in all the other build containers.
      - store_artifacts:
          path: build/libs
  eb-demo:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          command: |
            eb init my-environment -r $AWS_DEFAULT_REGION -p "arn:aws:elasticbeanstalk:us-east-1::platform/Corretto 11 running on 64bit Amazon Linux 2/3.1.8"
            eb create my-environment
            eb deploy my-environment
            eb status
          name: You may now use the EB CLI within this job
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb-build
      - eb-demo
          requires: [eb-build]
